# Generated by Django 6.0.1 on 2026-02-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_assigned_to'),
        ('user', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='user.userprofile'),
        ),
    ]
