# Generated by Django 6.0.3 on 2026-03-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MANAGING DIRECTOR', 'MANAGING DIRECTOR'), ('DEPARTMENT', 'DEPARTMENT')], max_length=200),
        ),
    ]
